version: '3.7'

services:
  mongodb:
    build: ./docker/mongodb-rs
    restart: always
    container_name: mongodb
    environment:
      MONGO_REPLICA_HOST: "localhost"
      MONGO_REPLICA_PORT: "27017"
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
